apiVersion: v1
entries:
  trident-installer:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2020-09-09T10:57:50.330703-06:00"
    description: Operator that installs NetApp/Trident
    digest: 50048f6a21f4004e968d0599b50413e6cbe8303f1adc22bcd06fe99752d5fe7e
    name: trident-installer
    type: application
    urls:
    - trident-installer-0.1.0.tgz
    version: 0.1.0
generated: "2020-09-09T10:57:50.327406-06:00"
